Tr origami
software-mansion/react-native-reanimated pull request #1161
Opened 2020-08-27 14:02 UTC by terrysahaidak

## Description

## Changes

2020-11-09 12:19 UTC, jakub-gonet commented
What's the status of this?

2020-11-10 19:26 UTC, terrysahaidak commented
Will update it tomorrow, thanks for reminding me.

2020-11-18 07:39 UTC, jakub-gonet commented
@terrysahaidak 🏓

2020-11-21 20:11 UTC, harterc1 requested changes

2020-11-21 20:11 UTC, harterc1 commented on src/reanimated2/SpringConfig.js
> +  'wroklet';
typo here

2020-11-23 11:30 UTC, terrysahaidak commented on src/reanimated2/SpringConfig.js
> +  'wroklet';
thanks, I'll update it later

2020-11-23 11:30 UTC, terrysahaidak commented
working on it right now :)

2020-12-31 10:34 UTC, jakub-gonet commented
@terrysahaidak 🏓

2021-02-09 13:34 UTC, jakub-gonet commented
@terrysahaidak 🏓 

Do you plan on working on this? Just checking so it doesn't go stale.

2021-03-12 10:31 UTC, jakub-gonet commented
@terrysahaidak 🏓

2021-03-26 08:42 UTC, mrousavy commented
@jakub-gonet 

![image](https://user-images.githubusercontent.com/15199031/112605365-857ebe00-8e17-11eb-9711-c7ff9b89c875.png)

just so you don't play by yourself

2022-02-16 17:10 UTC, closed without merging