Lazy imports/exports
software-mansion/react-native-reanimated pull request #1209
Opened 2020-09-08 13:20 UTC by radex

## Description

Hi. I've been profiling the launch time of my app, and optimizing the critical path to launch the app. I found reanimated to take ~30ms to launch (to import it), but very few of its exports are actually required to launch my app.

And so I applied the technique react-native uses (explicit export with getters that lazily require sub-modules) to make the reexport lazy. I didn't apply it completely, mostly just to the biggest culprits - animations/ which create very complicated proc()s that take a lot of time to send to native.

Is it ugly? Yes. Is it worth it? Sure. After this change, reanimated takes ~10ms to import.

## Test plan

I ran automated tests in this repo + ran manual tests on [Nozbe Teams](https://nozbe.com) to check for regressions.

2020-09-08 14:05 UTC, jakub-gonet requested changes
1. Formatting shouldn't be the part of this change, please keep only the exports change here.
2. Why did you update `yarn.lock`?
3. Please change the branch to `master`, we cherry-pick into v1 and not the other way around.

2020-10-20 09:29 UTC, jkadamczyk commented
Hey @radex! If you wouldn't mind applying the changes @jakub-gonet suggested, I would be happy to merge your PR after some additional testing.

I also spotted your PR in Gesture Handler https://github.com/software-mansion/react-native-gesture-handler/pull/1187

Looking forward to your changes!

2021-02-17 14:37 UTC, jakub-gonet commented
@radex 🏓

2022-02-16 17:11 UTC, piaskowyk commented
I close it because PR is inactive, but if someone wants to take care of this one I will reopen it with pleasure 🚀

2022-02-16 17:11 UTC, closed without merging