Add another ways to mark function as worklet.
software-mansion/react-native-reanimated pull request #1310
Opened 2020-10-06 05:59 UTC by Szymon20000

The pull-request adds two methods which are the new ways for telling babel that is should transform the function into a worklet. The first is `useWorkletCallback`:
```JS
useWorkletCallback(() => {...});
```
which is equivalent to
```JS
useCallback(() => {
  'worklet'
})
``` 

The second one is `createWorklet` which just lets us omit 'worklet' mark.
```JS
const worklet = createWorklet(() => {
  ...
});
```
behaves the same as
```
const worklet = () => {
   'worklet'
    ...
}

2020-10-06 06:02 UTC, terrysahaidak requested changes

2020-10-06 06:02 UTC, terrysahaidak commented on src/reanimated2/Hooks.js
> +export function useWorkletCallback(fun) {
You're missing deps here

2020-10-06 06:04 UTC, Szymon20000 commented on src/reanimated2/Hooks.js
> +export function useWorkletCallback(fun) {
Oh, true.

2020-10-06 06:05 UTC, terrysahaidak commented
I'll add TS typings in the following PR.

2020-10-06 13:41 UTC, kmagiera approved these changes

2020-10-06 15:43 UTC, terrysahaidak commented on react-native-reanimated.d.ts
> +      deps?: DependencyList
Just realized I put deps here too
```suggestion
      fn: (...args: A) => R
```

2020-10-06 15:44 UTC, terrysahaidak commented on react-native-reanimated-tests.tsx
> +  });
I should've to add deps here too.

```suggestion
  }, []);
```

2020-10-07 07:12 UTC, jfrolich commented
A note to make sure that it doesn't fail with this syntax:

```es6
import * as Reanimated from 'reanimated'

Reanimated.createWorklet(() => {
  ...
})
```

2020-10-07 07:17 UTC, terrysahaidak commented
https://github.com/software-mansion/react-native-reanimated/pull/1210 This PR should fix this type of imports as well. 

cc @jakub-gonet

2020-10-07 10:32 UTC, merged

2020-10-07 12:23 UTC, mrousavy commented
While I'm a big fan of this idea, I think it would be a better name to shorten `useWorkletCallback` to `useWorklet`. A 'worklet' if per definition something like a callback anyways, no?

Thoughts @kmagiera @terrysahaidak @Szymon20000 ?