[v1] Update interpolate `outputRange` type to allow strings
software-mansion/react-native-reanimated pull request #1437
Opened 2020-11-13 12:50 UTC by chj-damon

## Description

## Changes

## Test code and steps to reproduce

## Checklist

- [ ] Included code example that can be used to test this change
- [ ] Updated TS types
- [ ] Added TS types tests
- [ ] Added unit / integration tests
- [ ] Updated documentation
- [ ] Ensured that CI passes

2020-11-13 13:57 UTC, jakub-gonet requested changes
LGTM, left some minor comments.

2020-11-13 13:57 UTC, jakub-gonet commented on react-native-reanimated-tests.tsx
> +    outputRange: ['0%', '100%'],
We only support interpolating degrees in the string form.

```suggestion
    outputRange: ['0deg', '360deg'],
```

2020-11-13 13:57 UTC, jakub-gonet commented on react-native-reanimated.d.ts
> +    ): number;
Unrelated change.

2020-11-14 07:46 UTC, chj-damon commented
updated.

2020-11-14 17:44 UTC, jakub-gonet approved these changes
Looks great, thanks!

2020-11-14 17:45 UTC, merged