Concretize createAnimatedComponent
software-mansion/react-native-reanimated pull request #1698
Opened 2021-02-05 15:44 UTC by mrousavy

## Description

Until now `createAnimatedComponent` took the `ComponentType<P>` parameter, and returned a `ComponentType<AnimateProps<P>>` animated component as a result.

This added a few problems, such as the loss of information on whether a component is a class or a function component.

This PR concretizizes the function to return `ComponentClass<AnimateProps<P>>` if a class component was passed, and `FunctionComponent<AnimateProps<P>>` if a function component was passed.

## Test code and steps to reproduce

```tsx

const ReanimatedCircle = Reanimated.createAnimatedComponent(Circle);

function App() {
  const svgCircleRef = useRef<React.Component<CircleProps>>();

  return <ReanimatedCircle ref={svgCircleRef} />;
}
```

The above code now doesn't raise an error.

## Checklist

- [ ] Included code example that can be used to test this change
- [ ] Updated TS types
- [ ] Added TS types tests
- [ ] Added unit / integration tests
- [ ] Updated documentation
- [ ] Ensured that CI passes

2021-02-05 16:38 UTC, jakub-gonet requested changes
CI is failing.

Also, could you add some test cases for this change?

2021-02-05 16:40 UTC, mrousavy commented
@jakub-gonet oh yeah, looks like previous errors are now fixed with this PR.

Sorry for the sloppy PR, I'll add tests to this one (and the other) in a sec.

2021-02-09 10:27 UTC, mrousavy commented
I added some tests @jakub-gonet - let's hope CI goes green 😄

2021-02-09 13:01 UTC, jakub-gonet approved these changes
Looks good, thanks!

2021-02-09 13:02 UTC, merged