Install global bindings for executor factory
software-mansion/react-native-reanimated pull request #1704
Opened 2021-02-09 14:41 UTC by mrousavy

## Description

After upgrading to RN 0.64 and enabling Hermes, I noticed that my console.logs were gone.

That's the only thing I saw in metro:

![](https://user-images.githubusercontent.com/15199031/107367690-e52b3f00-6adf-11eb-8259-f60ea490e7e1.png)

After a long journey of debugging (see https://github.com/facebook/metro/issues/635#issuecomment-775939213) I finally found the weird side-effect our custom executor factory creation was having.

This is our `jsExecutorFactoryForBridge` func's return:

```objc
  return std::make_unique<ExecutorFactory>([weakSelf, bridge](facebook::jsi::Runtime &runtime) {
    if (!bridge) {
      return;
    }
    __typeof(self) strongSelf = weakSelf;
    if (strongSelf) {
      #if RNVERSION < 63
        auto callInvoker = std::make_shared<react::BridgeJSCallInvoker>(bridge.reactInstance);
        auto reanimatedModule = reanimated::createReanimatedModule(callInvoker);
      #else
        auto reanimatedModule = reanimated::createReanimatedModule(bridge.jsCallInvoker);
      #endif
      runtime.global().setProperty(runtime,
                                   jsi::PropNameID::forAscii(runtime, "__reanimatedModuleProxy"),
                                   jsi::Object::createFromHostObject(runtime, reanimatedModule)
      );
    }
  });
```

This is from rn-tester:

```objc
  __weak __typeof(self) weakSelf = self;
#if RCT_USE_HERMES
  return std::make_unique<facebook::react::HermesExecutorFactory>(
#else
  return std::make_unique<facebook::react::JSCExecutorFactory>(
#endif
      facebook::react::RCTJSIExecutorRuntimeInstaller([weakSelf, bridge](facebook::jsi::Runtime &runtime) {
        if (!bridge) {
          return;
        }
        __typeof(self) strongSelf = weakSelf;
        if (strongSelf) {
          facebook::react::RuntimeExecutor syncRuntimeExecutor =
              [&](std::function<void(facebook::jsi::Runtime & runtime_)> &&callback) { callback(runtime); };
          [strongSelf->_turboModuleManager installJSBindingWithRuntimeExecutor:syncRuntimeExecutor];
        }
      }));
```

As you can see, we're missing `RCTJSIExecutorRuntimeInstaller` which is responsible for binding nativePerformanceNow, console, etc.

I have no idea why this was also affecting the React JS thread, since this function should only be called for the worklet thread, so that's probably why it was also overriding and unsetting the globals for the React JS thread.

## Changes

* Correctly install bindings using `RCTJSIExecutorRuntimeInstaller` for the JSI Executor.

### Before

no logs in console (no `global.console`, no `global.nativePerformanceNow`)

### After

logs in console 🎉

2021-02-09 15:12 UTC, mrousavy commented
For reference, [here's the `AppDelegate.mm:jsExecutorFactoryForBridge `](https://github.com/facebook/react-native/blob/master/packages/rn-tester/RNTester/AppDelegate.mm#L160-L192) from facebook's rn-tester.

2021-02-09 21:45 UTC, gilbertl commented
Based on the above description, this should fix https://github.com/software-mansion/react-native-reanimated/issues/1542#issuecomment-766667082

2021-02-09 21:50 UTC, mrousavy commented
@gilbertl right, that should work. Can you test that real quick? Simply apply the change from this PR using patch-package and create a new build and check out your Instabug logs

2021-02-10 07:49 UTC, gilbertl commented
Unfortunately, creating a patch for react-native-reanimated results in

`• Creating temporary folder
• Installing react-native-reanimated@2.0.0-rc.1 with yarn
• Diffing your files with clean files
Error: ELOOP: too many symbolic links encountered, stat '/var/folders/45/g30y1xtj3xvd8k4lw2k3s0f80000gn/T/tmp-41895Bp3m9aQK6YdP/node_modules/react-native-reanimated/android/src/main/Common'
    at Object.statSync (fs.js:1016:3)
    at Object.statSync (/Users/gilbertleung/Projects/shuffle/packages/reactnative/node_modules/klaw-sync/node_modules/graceful-fs/polyfills.js:308:16)
    at klawSync (/Users/gilbertleung/Projects/shuffle/packages/reactnative/node_modules/klaw-sync/klaw-sync.js:16:24)
    at klawSync (/Users/gilbertleung/Projects/shuffle/packages/reactnative/node_modules/klaw-sync/klaw-sync.js:24:30)
    at klawSync (/Users/gilbertleung/Projects/shuffle/packages/reactnative/node_modules/klaw-sync/klaw-sync.js:24:30)
    at Object.klawSync [as default] (/Users/gilbertleung/Projects/shuffle/packages/reactnative/node_modules/klaw-sync/klaw-sync.js:24:30)
    at Object.removeIgnoredFiles (/Users/gilbertleung/Projects/shuffle/packages/reactnative/node_modules/patch-package/dist/filterFiles.js:10:24)
    at Object.makePatch (/Users/gilbertleung/Projects/shuffle/packages/reactnative/node_modules/patch-package/dist/makePatch.js:122:23)
    at /Users/gilbertleung/Projects/shuffle/packages/reactnative/node_modules/patch-package/dist/index.js:48:25
    at Array.forEach (<anonymous>) {
  errno: -62,
  syscall: 'stat',
  code: 'ELOOP',
  path: '/var/folders/45/g30y1xtj3xvd8k4lw2k3s0f80000gn/T/tmp-41895Bp3m9aQK6YdP/node_modules/react-native-reanimated/android/src/main/Common'
}
/Users/gilbertleung/Projects/shuffle/packages/reactnative/node_modules/patch-package/dist/makePatch.js:183
        throw e;
        ^`

2021-02-10 08:26 UTC, mrousavy commented
@gilbertl not sure what went wrong on your end, but it's just a single file. Make sure the REA folder is clean:

```
rm -rf node_modules/react-native-reanimated
```

and then modify that file (`UIResponder+Reanimated.mm`), then immediately run:

```
npx patch-package react-native-reanimated
```

2021-02-10 08:40 UTC, gilbertl commented
> @gilbertl not sure what went wrong on your end, but it's just a single file. Make sure the REA folder is clean:
> 
> ```
> rm -rf node_modules/react-native-reanimated
> ```
> 
> and then modify that file (`UIResponder+Reanimated.mm`) with my changes here, then immediately run:
> 
> ```
> npx patch-package react-native-reanimated
> ```

After I rm -rf, there's nothing left in that directory so it's not possible to modify UIResponder+Reanimated.mm ? 

I've already tried yarn cleaning, yarn, and the ELOOP error still persists

2021-02-10 08:42 UTC, mrousavy commented
@gilbertl my bad, yeah `npm i` after the cleaning. Either way, you should also be able to just modify the file and then build the release on your machine.

2021-02-10 11:07 UTC, piaskowyk requested changes
Once again - thanks for solid investigations 🙌
I added some suggestions to change to make backward compatibility in code because `RCTJSIExecutorRuntimeInstaller` has appeared since RN64.
These changes shouldn't affect other components because `RCTJSIExecutorRuntimeInstaller` functionality was moved from existing function to a new place: https://github.com/facebook/react-native/commit/941bc0ec195716e6a505a3c3a67f97a87ea9bcdc (from `JSCExecutorFactory::createJSExecutor` to `RCTJSIExecutorRuntimeInstaller`)

2021-02-10 11:11 UTC, mrousavy commented
Oh right! sometimes I forget about backwards compatibility 😅 on it

2021-02-10 11:21 UTC, mrousavy commented
@piaskowyk done 🏓

2021-02-10 11:52 UTC, piaskowyk approved these changes

2021-02-10 12:13 UTC, merged