Fix, replace for..of on for loop
software-mansion/react-native-reanimated pull request #2096
Opened 2021-06-02 23:02 UTC by NikitaDudin

## Description

## Changes

## Test code and steps to reproduce

## Checklist

- [ ] Included code example that can be used to test this change
- [ ] Updated TS types
- [ ] Added TS types tests
- [ ] Added unit / integration tests
- [ ] Updated documentation
- [ ] Ensured that CI passes

2021-06-04 10:08 UTC, piaskowyk commented
Could you provide an example code to reproduce this issue?

2021-06-04 13:19 UTC, NikitaDudin commented
@piaskowyk https://github.com/software-mansion/react-native-reanimated/pull/1879#issuecomment-853412859

2021-06-06 11:41 UTC, mrousavy commented
Looks like the JS runtime (or the babel plugin) doesn't whitelist the `iterator` as a native prop. `for..of` uses `[Symbol.iterator]`, no?

2021-06-08 12:55 UTC, terrysahaidak commented on src/reanimated2/Hooks.ts
> +      const item = prop[i]
```suggestion
      const item = prop[i];
```

2021-06-09 07:59 UTC, piaskowyk requested changes
Thanks for PR 🙌
Could you just change `i += 1` to `++i`?

2021-06-09 08:04 UTC, piaskowyk commented
@NikitaDudin which version of babel and Hermes do you use?

2021-06-09 10:55 UTC, NikitaDudin commented
@piaskowyk hermes: 0.7.2 babel: 7.9.0

2021-06-09 10:57 UTC, NikitaDudin commented
> Thanks for PR 🙌
> Could you just change `i += 1` to `++i`?

Are you sure you should change to the prefix form `++i`?  May be `i++`?

2021-06-09 11:11 UTC, piaskowyk commented
> > Thanks for PR 🙌
> > Could you just change `i += 1` to `++i`?
> 
> Are you sure me should change to the prefix form `++i`? May be `i++`?

Yes, `++i` is a little faster than `i++` and `i++` is faster than `i += 1` 😅. Sure it can depend on the runtime version, but general idea is that. I think that every above expression is the same readable, but if we can choose faster - why not - what do you think? 🤔

2021-06-09 11:17 UTC, piaskowyk commented
I generally don't pick on things like that because this doesn't make a big difference, but I optimized it last time and I want to make it as faster as possible. 😅

2021-06-09 11:47 UTC, piaskowyk approved these changes

2021-06-09 11:47 UTC, piaskowyk commented
@NikitaDudin good job, thanks 💪

2021-06-09 11:47 UTC, merged