Fixed float with scientific notation to string conversion
software-mansion/react-native-reanimated pull request #2210
Opened 2021-07-22 13:01 UTC by jmysliv

## Description

During animations, property value is often converted between string and float. When the animation value gets too small or too big, it converts to string with scientific notation. It is then interpreted as a value with suffix `e` and is converted back to float without scientific notation which results in the unexpected and rapid change of the animation value. 

![Screenshot 2021-07-22 at 13 01 24](https://user-images.githubusercontent.com/48885911/126641410-f14783fd-c25b-46ab-a9b3-0420c91b0625.png)

I've changed float to string conversion, so it is now converted without scientific notation.

Fixes #2170 

## Changes
- changed animation value float to string conversion

2021-07-23 11:54 UTC, mrousavy commented
Does `toLocaleString` require Intl? If so, that function will be incredibly slow on Hermes.

2021-07-26 07:08 UTC, piaskowyk commented
@mrousavy good point! @jmysliv we need to check the performance of this solution.

2021-07-26 07:47 UTC, jmysliv commented
@mrousavy @piaskowyk I'll check the performance of `toLocaleString` conversion and custom conversion and I'll let you know what are the results.

2021-07-26 09:09 UTC, jakub-gonet commented
I think we should Intl.NumberFormat object before doing the conversion, as described [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString#performance).

And if still this method will be slow we may use [this snippet from SO](https://stackoverflow.com/a/46545519) (with proper atribution of course).

2021-07-26 09:44 UTC, jmysliv commented
I've tested all three options in 100k iteration, custom conversion similar to a snippet from SO is about 100 times faster than `toLocaleString` method and about 4 times faster than `format` method when we create Intl.NumberFormat object earlier.

2021-07-26 09:45 UTC, mrousavy commented
@jmysliv did you also compare performance of Hermes to JSC?

2021-07-26 09:46 UTC, mrousavy commented
Why is the value even converted to a string in the first place? @piaskowyk

2021-07-27 06:40 UTC, jmysliv commented
@mrousavy there is some issue with intl support on Hermes (https://github.com/facebook/hermes/issues/23), so if we don't want to use any workaround I think the best and fastest option will be using [manual conversion](https://stackoverflow.com/questions/1685680/how-to-avoid-scientific-notation-for-large-numbers-in-javascript/46545519#46545519).

2021-07-28 11:32 UTC, jakub-gonet commented
@jmysliv Please add SO link if you didn't write that function by yourself:
- https://meta.stackoverflow.com/a/253622
- https://stackoverflow.blog/2009/06/25/attribution-required/

2021-07-28 15:14 UTC, jakub-gonet approved these changes

2021-07-28 15:18 UTC, mrousavy commented
Somehow I have a feeling that this code is not the fastest (especially because of the array allocation + joining) and this is a very hot spot in the codebase...

2021-07-28 15:31 UTC, jakub-gonet commented
> Somehow I have a feeling that this code is not the fastest (especially because of the array allocation + joining) and this is a very hot spot in the codebase...

And string creation if we're on that. But good point, maybe we should do some benchmarking.

2021-07-30 07:54 UTC, jmysliv commented
@mrousavy I've tested performance before and after this change and I didn't encounter any significant frame drop. 

> Somehow I have a feeling that this code is not the fastest (especially because of the array allocation + joining) and this is a very hot spot in the codebase...

I can instead of array join perform string concatenation, which as far as I know is faster. I'm also open to any other suggestions or ideas that may speed up this code.

2021-08-09 08:20 UTC, piaskowyk requested changes
We need just use this https://github.com/software-mansion/react-native-reanimated/pull/2210 and change the regex rule.

2021-08-09 10:41 UTC, jmysliv commented
I'm closing this because #2238 will fix this issue without a performance drop.

2021-08-09 10:41 UTC, closed without merging