Fix crash when handling event containing NaN or INF values for android
software-mansion/react-native-reanimated pull request #2901
Opened 2022-01-28 18:45 UTC by michaelknoch

## Description
Applies the iOS fix in https://github.com/software-mansion/react-native-reanimated/pull/2896 for android.

## Changes
Fix crash when handling event containing NaN or INF values
- Added `foo` method which add bouncing animation
- Updated `about.md` docs
- Added caching in CI builds

## Test code and steps to reproduce
tested by manually inserting NaN and INF values in receiveEvent.java

## Checklist

- [ ] Included code example that can be used to test this change
- [ ] Updated TS types
- [ ] Added TS types tests
- [ ] Added unit / integration tests
- [ ] Updated documentation
- [ ] Ensured that CI passes

2022-01-28 18:45 UTC, michaelknoch commented
cc @tomekzaw @piaskowyk

2022-01-28 22:36 UTC, tomekzaw requested changes
Thanks for the PR! Indeed, we should handle this on Android analogously as in #2896. BTW Here's the proof that `WritableMap::toString` also uses `folly::toJson` under the hood: https://github.com/facebook/react-native/blob/8bd3edec88148d0ab1f225d2119435681fbbba33/ReactAndroid/src/main/jni/react/jni/NativeMap.cpp#L19

I left two suggestions in the comments. Once they are resolved, we are ready to merge I think 😄

2022-01-28 22:36 UTC, tomekzaw commented on android/src/main/cpp/headers/NativeProxy.h
> +      if (event != nullptr) {
I'd suggest moving `try/catch` block into `if`.

2022-01-28 22:36 UTC, tomekzaw commented on android/src/main/cpp/headers/NativeProxy.h
> +    } catch (const std::exception &) {
```suggestion
    } catch (folly::json::parse_error &) {
```

2022-01-29 01:29 UTC, michaelknoch commented on android/src/main/cpp/headers/NativeProxy.h
> +      } catch (std::exception) {
apparently `catch(folly::json::parse_error)` doesn't seem to catch the error @tomekzaw

2022-01-29 02:02 UTC, michaelknoch commented
thx @tomekzaw , I addressed your feedback

2022-01-29 08:17 UTC, tomekzaw approved these changes
Looks good to me!

2022-02-01 09:28 UTC, michaelknoch commented
you think we can get this (and the ios fix) into 2.4.0 release @tomekzaw

2022-02-01 09:40 UTC, tomekzaw commented
> you think we can get this (and the ios fix) into 2.4.0 release @tomekzaw

Yes, definitely. These two PRs resolve one of the most mysterious bugs hiding over there. Just waiting to get it double-reviewed (probably tomorrow).

2022-02-01 13:40 UTC, kmagiera approved these changes

2022-02-02 07:56 UTC, piaskowyk approved these changes

2022-02-02 07:59 UTC, merged