Add color interpolation widget to docs
software-mansion/react-native-reanimated pull request #3894
Opened 2022-12-30 16:25 UTC by graszka22

## Summary
Adds the following section and a widget to the docs:
![Screenshot 2022-12-30 at 17 23 16](https://user-images.githubusercontent.com/6280457/210091463-8f92fc6b-3e84-4764-af63-84d732b4fa53.png)

2023-01-03 09:46 UTC, tomekzaw requested changes
I'd like to propose some UX improvements:

1. Let's use lime `#00ff00` and pink `#ffc0cb` as the initial colors. The motivation is that these colors perfectly illustrate the differences between each interpolation mode:
<img width="236" alt="rgb" src="https://user-images.githubusercontent.com/20516055/210329143-16742b1f-f856-43e9-9638-79034514659b.png">
<img width="240" alt="1" src="https://user-images.githubusercontent.com/20516055/210328715-a7f56f78-3eb7-49f3-8c96-c7510b15f298.png">
<img width="243" alt="0" src="https://user-images.githubusercontent.com/20516055/210328710-f01e26cf-0fbb-425d-b76c-df4e9aa75990.png">

2. I'm a huge fan of these color progress bars that you came up with. However, currently, it's not possible to see all 4 "predefined" modes at once (RGB, RGB+gamma, HSV, HSV+corrected). I would like to suggest adding the following table directly below color pickers:

| Mode | Result |
|-|:-:|
| RGB without gamma correction | <img width="234" alt="Zrzut ekranu 2023-01-3 o 10 24 46" src="https://user-images.githubusercontent.com/20516055/210330039-ec099d77-4ecc-41fa-922e-be87dae1085e.png"> |
| RGB with gamma = 2.2 (default) | <img width="231" alt="Zrzut ekranu 2023-01-3 o 10 25 06" src="https://user-images.githubusercontent.com/20516055/210330095-7c571047-2967-4d09-a368-8d4d7e0b2c9d.png"> |
| HSV without correction | <img width="233" alt="Zrzut ekranu 2023-01-3 o 10 25 28" src="https://user-images.githubusercontent.com/20516055/210330157-d02cff96-4ade-42a7-86f4-b4e81eba6842.png"> |
| HSV with correction | <img width="230" alt="Zrzut ekranu 2023-01-3 o 10 25 44" src="https://user-images.githubusercontent.com/20516055/210330194-4c0100b1-9a05-4f72-a706-8aa669f60456.png"> |

3. Instead of having two separate color animation boxes ("RGB colorspace" and "HSV colorspace", I would like to suggest having only one and adding a following form:
* Color space: selectbox with two options: RGB, HSV
* Gamma: numeric input (disabled if HSV is selected)
* Use HSV corrected interpolation: checkbox (disabled if RGB is selected)

4. Currently, when you press "Run animation" button for the second time, nothing happens. It would be great if the animation could go back to the original color when pressed again, and so on. You can use [this](https://github.com/software-mansion/react-native-reanimated/blob/63960981c7b2b613bf99cc56f4fb7ed810ad57cb/FabricExample/src/TransformExample.tsx#L29-L32) code snippet.

2023-01-03 09:46 UTC, tomekzaw commented on docs/docs/api/miscellaneous/interpolateColors.mdx
> +  through many other hues. This option allows to reduce the number of hues in such cases by treating hsv hues like a circular spectrum and choosing
```suggestion
  through many other hues. This option allows to reduce the number of hues in such cases by treating HSV hues like a circular spectrum and choosing
```

2023-01-03 16:53 UTC, tomekzaw commented
Some final suggestions:
1. Move "Example" section directly after "Options explanation"
2. Rename "Interpolate:" section header to "Playground"
3. Rename "Animation:" section header to "Live demo" 
4. Change gamma numeric input step from 1 to 0.1, set min value to 0.1 and max value to 10
5. I've changed my mind - instead of disabling the input/checkbox (depending on color space), make it hidden (i.e. render it conditionally)

2023-01-03 17:50 UTC, tomekzaw commented on docs/docs/api/miscellaneous/interpolateColors.mdx
> +  may appear darker than it should. That's why when iterpolating we convert sRGB to linear space first and then convert
```suggestion
  may appear darker than it should. That's why when interpolating we convert sRGB to linear space first and then convert
```

2023-01-03 17:50 UTC, tomekzaw commented on docs/docs/api/miscellaneous/color_widget/styles.module.css
> +    font-size:medium;
```suggestion
    font-size: medium;
```

2023-01-05 11:50 UTC, piaskowyk approved these changes

2023-01-05 12:23 UTC, tomekzaw approved these changes

2023-01-09 10:07 UTC, merged