Disable `HERMES_ENABLE_DEBUGGER` when building Reanimated 2 AAR package
software-mansion/react-native-reanimated pull request #3956
Opened 2023-01-16 15:18 UTC by tomekzaw

## Summary

Fixes #3952.

## Test plan

1. Build Reanimated 2 package on CI
2. Create a new RN 0.70.6 app with Reanimated
3. Copy BokehExample to App.js
4. Build the app in release mode for Android
5. Check if the runtime error is gone

2023-01-16 16:41 UTC, piaskowyk approved these changes

2023-01-16 16:43 UTC, piaskowyk requested changes
Let's just fix CI, the changes are ok 👍

2023-01-17 12:51 UTC, piaskowyk approved these changes

2023-01-17 12:51 UTC, merged

2024-11-29 01:28 UTC, txt2954 reviewed
php.policy CPI on beta license interstate trade on national license

2024-11-29 01:28 UTC, txt2954 commented on android/build.gradle
[1-active-state-timeline.csv](https://github.com/user-attachments/files/17953352/1-active-state-timeline.csv)