Optimize hot code-paths in uAS
software-mansion/react-native-reanimated pull request #3980
Opened 2023-01-19 22:52 UTC by kmagiera

## Summary

This is another attempt at optimizing useAnimatedStyle and style updater after #395 got reverted. In this approach we omit Object.assign completely in favor of just using newValues object. Since newValues may contain animation objects, we use one of the initial loops from the updater to extract non-animated-props such that they can be used later on instead of using a call to `filerAnimatedProps`. We also replace `styleDiff` that'd allocate new object by `shallowEqual` that only does comparison. We've been using newValues to update the values anyways and so the diff wasn't used. In addition there was a bug before where we had `if (diff)` check – this wasn't correct as in case there were no changes between the objects, the diff would be an empty object and the check would pass.

## Test plan

Tested on a bunch of different examples. Make sure to verify on examples that use animations inside uAS.

2023-02-06 21:48 UTC, tomekzaw requested changes
Tested on Example app on iOS as well as FabricExample on Android. Everything seems to work just fine except for BokehExample 😢

2023-02-16 13:38 UTC, kmagiera commented
I think this error was fixed in f156b1294bccd052d0fc09252bbf3a5e30eb81ad – can I get this approved then 🙏

2023-02-16 13:44 UTC, tomekzaw approved these changes

2023-02-16 13:47 UTC, piaskowyk approved these changes

2023-02-16 13:57 UTC, merged

2023-05-15 10:10 UTC, Latropos commented on src/reanimated2/hook/useAnimatedStyle.ts
> +      updateProps(viewDescriptors, nonAnimatedNewValues, maybeViewRef);
Why do we update nonAnimatedNewValues?