[Plugin] [0/9] Split plugin into separate files and add bundling option.
software-mansion/react-native-reanimated pull request #4209
Opened 2023-03-13 15:39 UTC by tjzel

## Summary

More work on plugin refactorization. This is simply splitting the code into files without any changes to it and adding `esbuild` bundler to generate a single file.

## Test plan

Run `yarn jest` and build Example app.

2023-03-13 15:40 UTC, tjzel commented on plugin/package.json
> +    "bundle": "yarn esbuild src/plugin.js --bundle --external:@babel --external:convert-source-map --external:fs --platform=node --sourcemap=linked --outfile=index.js && rm src/*.js src/*.js.map",
I am not sure if removing compiled source files is a fail-safe option.

2023-03-24 09:17 UTC, tomekzaw requested changes

2023-03-24 09:17 UTC, tomekzaw commented on plugin/package.json
> +    "bundle": "yarn esbuild src/plugin.js --bundle --external:@babel --external:convert-source-map --external:fs --log-level=warning --platform=node --sourcemap=linked --outfile=index.js && rm src/*.
Is it possible to specify these options in some kind of esbuild config file?

2023-03-24 09:17 UTC, tomekzaw commented on plugin/package.json
> +    "bundle": "yarn esbuild src/plugin.js --bundle --external:@babel --external:convert-source-map --external:fs --log-level=warning --platform=node --sourcemap=linked --outfile=index.js && rm src/*.
Can we move `rm src/*.js src/*.js.map` to a separate `clean` script and call it inside `generate`?

2023-03-24 09:17 UTC, tomekzaw commented on plugin/src/commonFunctions.ts
> +}
```suggestion
}

```

2023-03-24 09:17 UTC, tomekzaw commented on plugin/src/commonFunctions.ts
> +}
```suggestion
}

```

2023-03-24 09:17 UTC, tomekzaw commented on plugin/src/commonFunctions.ts
> +export { hash, isRelease, shouldGenerateSourceMap };
Please use `export function` as we already do throughout our codebase 🙏

2023-03-27 14:48 UTC, tomekzaw commented on plugin/src/commonInterfaces.ts
> +import * as BabelCore from '@babel/core';
types.ts

2023-03-27 14:53 UTC, tomekzaw commented on plugin/src/commonObjects.ts
> +export const globals = new Set([
rename file plz

2023-03-27 16:33 UTC, tjzel commented on plugin/package.json
> +    "clean": "rm src/*.js src/*.js.map",
```
———————————lib?———————————
⠀⣞⢽⢪⢣⢣⢣⢫⡺⡵⣝⡮⣗⢷⢽⢽⢽⣮⡷⡽⣜⣜⢮⢺⣜⢷⢽⢝⡽⣝
⠸⡸⠜⠕⠕⠁⢁⢇⢏⢽⢺⣪⡳⡝⣎⣏⢯⢞⡿⣟⣷⣳⢯⡷⣽⢽⢯⣳⣫⠇
⠀⠀⢀⢀⢄⢬⢪⡪⡎⣆⡈⠚⠜⠕⠇⠗⠝⢕⢯⢫⣞⣯⣿⣻⡽⣏⢗⣗⠏⠀
⠀⠪⡪⡪⣪⢪⢺⢸⢢⢓⢆⢤⢀⠀⠀⠀⠀⠈⢊⢞⡾⣿⡯⣏⢮⠷⠁⠀⠀
⠀⠀⠀⠈⠊⠆⡃⠕⢕⢇⢇⢇⢇⢇⢏⢎⢎⢆⢄⠀⢑⣽⣿⢝⠲⠉⠀⠀⠀⠀
⠀⠀⠀⠀⠀⡿⠂⠠⠀⡇⢇⠕⢈⣀⠀⠁⠡⠣⡣⡫⣂⣿⠯⢪⠰⠂⠀⠀⠀⠀
⠀⠀⠀⠀⡦⡙⡂⢀⢤⢣⠣⡈⣾⡃⠠⠄⠀⡄⢱⣌⣶⢏⢊⠂⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⢝⡲⣜⡮⡏⢎⢌⢂⠙⠢⠐⢀⢘⢵⣽⣿⡿⠁⠁⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠨⣺⡺⡕⡕⡱⡑⡆⡕⡅⡕⡜⡼⢽⡻⠏⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⣼⣳⣫⣾⣵⣗⡵⡱⡡⢣⢑⢕⢜⢕⡝⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⣴⣿⣾⣿⣿⣿⡿⡽⡑⢌⠪⡢⡣⣣⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⡟⡾⣿⢿⢿⢵⣽⣾⣼⣘⢸⢸⣞⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠁⠇⠡⠩⡫⢿⣝⡻⡮⣒⢽⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
—————————————————————————————
```

2023-03-28 10:02 UTC, tomekzaw commented on plugin/tsconfig.json
> +    "rootDir": "src"
```suggestion
    "rootDir": "src/"
```

2023-03-28 10:02 UTC, tomekzaw approved these changes
👏

2023-03-28 11:06 UTC, merged