iOS scheduler optimisation fix
software-mansion/react-native-reanimated pull request #4734
Opened 2023-07-14 08:54 UTC by michalmaka

## Summary

I've noticed that `weak_ptr` for `runtimeManager` in iOS scheduler has executed `lock` method but returned `shared_ptr` is not used and thus deallocation immediately. In that case, if we just want to know whether `runtimeManager` `shared_ptr` is alive it's more performant to use `expired` method on `weak_ptr`.

I removed also some dead code:

- in `scheduleOnUI` there was unnecessary block of code checking if it's executed on main thread. If it is on main thread it returns from function several lines above the block and won't be executed.
- unnecessary virtual empty destructor for `REAIOSScheduler`. Base class has already virtual destructor and marking this again does not change anything. 

## Test plan

Check iOS application if works fine.

2023-07-14 10:27 UTC, tomekzaw requested changes

2023-07-14 10:27 UTC, tomekzaw commented on ios/native/REAIOSScheduler.h
> -  virtual ~REAIOSScheduler();
`REAIOSScheduler` extends `Scheduler` which has virtual methods so it needs to have a virtual destructor as well. We can move the implementation from .cpp to .h file if possible.

2023-07-14 10:27 UTC, tomekzaw commented on ios/native/REAIOSScheduler.mm
> -  }
Indeed, this block is no longer relevant (confirmed with @kmagiera).

2023-07-17 07:32 UTC, michalmaka commented on ios/native/REAIOSScheduler.mm
> +  const auto runtimeManagerExpired = runtimeManager.expired();
done

2023-07-17 07:42 UTC, tomekzaw commented on Common/cpp/Tools/Scheduler.h
> +  std::weak_ptr<RuntimeManager> weakRuntimeManager;
```suggestion
  std::weak_ptr<RuntimeManager> weakRuntimeManager_;
```

2023-07-17 08:27 UTC, tomekzaw approved these changes
Thanks for this PR! 👏

2023-07-17 08:47 UTC, piaskowyk approved these changes

2023-07-17 10:33 UTC, merged