Make babel version detection more verbose
software-mansion/react-native-reanimated pull request #4791
Opened 2023-07-21 17:57 UTC by tjzel

## Summary

Currently the error tells us that something is wrong but we don't have a clue what could be causing it. This PR makes error more verbose, displaying code of the offending worklet. I also added some cheeky Example for that purpose.

## Test plan

Run new `BabelVersioningExample`

🚀

2023-07-21 21:51 UTC, tomekzaw requested changes

2023-07-21 21:51 UTC, tomekzaw commented on app/src/examples/BabelVersioningExample.tsx
> +    backgroundColor: '#4488DDFF',
```suggestion
    backgroundColor: '#4488dd',
```

2023-07-21 21:51 UTC, tomekzaw commented on app/src/examples/BabelVersioningExample.tsx
> +function EvilButton({ version, long }: { version?: string; long?: boolean }) {
```suggestion
interface EvilButtonProps {
  version?: string;
  long?: boolean;
}

function EvilButton({ version, long }: EvilButtonProps) {
```

2023-07-21 21:51 UTC, tomekzaw commented on app/src/examples/BabelVersioningExample.tsx
> +}
Not really sure if we need these functions since we only call them once

2023-07-21 21:51 UTC, tomekzaw commented on app/src/examples/BabelVersioningExample.tsx
> +      style={[styles.button, pressed && { backgroundColor: '#3366DDFF' }]}
```suggestion
      style={[styles.button, pressed && { backgroundColor: '#3366dd' }]}
```

2023-07-21 21:51 UTC, tomekzaw commented on app/src/examples/BabelVersioningExample.tsx
> +      }}
```suggestion
      onPressIn={() => setPressed(true)}
```

2023-07-21 21:51 UTC, tomekzaw commented on app/src/examples/BabelVersioningExample.tsx
> +      }}>
```suggestion
      onPressOut={handlePressOut}>
```

2023-07-21 21:51 UTC, tomekzaw commented on app/src/examples/BabelVersioningExample.tsx
> +      <EvilButton long={true} />
this is kinda crazy

2023-07-21 21:51 UTC, tomekzaw commented on app/src/examples/index.ts
> +    title: 'Babel versioning',
Not really sure if this name tells the whole story behind the example

2023-07-24 09:43 UTC, tjzel commented on app/src/examples/BabelVersioningExample.tsx
> +      <EvilButton long={true} />
wdym

2023-07-24 11:50 UTC, tomekzaw commented on src/reanimated2/shareables.ts
> +    // need to make shareable clones when `runOnJS` is called on JS thread.
revert dis

2023-07-24 11:50 UTC, tomekzaw commented on src/reanimated2/shareables.ts
> +// and then you get into call stack exceeded. Use _log instead (on UI).
revert dis

2023-07-24 11:50 UTC, tomekzaw commented on app/src/examples/index.ts
> +  },
```suggestion
  BabelVersionCheckExample: {
    icon: '📦',
    title: 'Babel version check',
    screen: BabelVersionCheckExample,
  },
```

2023-07-24 11:50 UTC, tomekzaw commented on app/src/examples/BabelVersioningExample.tsx
> +function offender() {
```suggestion
function shortOffender() {
```

2023-07-24 11:50 UTC, tomekzaw commented on app/src/examples/BabelVersioningExample.tsx
> +  long?: boolean;
```suggestion
  version: string;
  long: boolean;
```

2023-07-24 11:50 UTC, tomekzaw commented on app/src/examples/BabelVersioningExample.tsx
> +      onPressIn={() => setPressed(true)}
remove dis

2023-07-24 15:22 UTC, tjzel reviewed
🎬

2023-07-24 15:22 UTC, tomekzaw approved these changes
![obraz](https://github.com/software-mansion/react-native-reanimated/assets/20516055/6177a94b-10c7-4013-99b7-afa25129a00e)

2023-07-24 15:23 UTC, merged