Remove infuriating docs lint from precommit
software-mansion/react-native-reanimated pull request #4795
Opened 2023-07-21 18:38 UTC by tjzel

## Summary

Currently docs have some issue while linting that some file couldn't be found by the linter and is extremely annoying when trying to commit, being forced to commit without precommit check.

Guess automatically linting docs waits for better times.

2023-07-21 21:38 UTC, tomekzaw commented
https://www.youtube.com/watch?v=VjEq-r2agqc&t=77s

2023-07-21 21:38 UTC, tomekzaw requested changes
https://www.youtube.com/watch?v=VjEq-r2agqc&t=77s

2023-07-22 07:31 UTC, efstathiosntonas commented
lol @tomekzaw. Lintere masturbetele

2023-07-24 14:13 UTC, tomekzaw approved these changes

2023-07-24 14:13 UTC, merged