Add macos app
software-mansion/react-native-reanimated pull request #4898
Opened 2023-08-08 12:00 UTC by jfedak

## Summary
This PR adds a macOS app using React Native (see [react-native-macos docs](https://microsoft.github.io/react-native-windows/docs/rnm-getting-started))

## Test plan
This app builds and runs on macOS. In order to run this app on your own, follow `README.md`.

2023-08-08 15:48 UTC, tomekzaw commented
Works for me ✅ 

<img width="1136" alt="screenshot" src="https://github.com/software-mansion/react-native-reanimated/assets/20516055/202942f3-c5b8-46da-bb89-cfabd02e385b">

2023-08-08 15:48 UTC, tomekzaw requested changes

2023-08-08 15:48 UTC, tomekzaw commented on MacOSExample/README.md
> +### Troubleshoot
```suggestion
### Troubleshooting
```

2023-08-08 15:48 UTC, tomekzaw commented on MacOSExample/README.md
> +If you have trouble with building the app, try running
```suggestion
If you have trouble with building the app, try running

```

2023-08-08 15:48 UTC, tomekzaw commented on MacOSExample/README.md
> +rm -rf Pods build Podfile.lock
```suggestion
rm -rf Pods Podfile.lock build
```

2023-08-08 18:10 UTC, tomekzaw approved these changes

2023-08-09 10:07 UTC, piaskowyk approved these changes

2023-08-09 10:10 UTC, merged