Fix assigning RN `ViewStyle.style` type to Animated components `style`
software-mansion/react-native-reanimated pull request #4899
Opened 2023-08-08 16:50 UTC by tjzel

## Summary

This is a continuation of #4881 - our utility type `AnimatedTransform` allowed `string` as transforms but only as an array of strings. This PR only fixes non-functional assignment of a potential string to `transform` in style.

## Test plan

Before, the following code yielded errors:

```TSX
import React from 'react';
import type { ViewStyle } from 'react-native';
import Animated from 'react-native-reanimated';

declare const style: ViewStyle;

function App() {
  return 
      <Animated.View style={style} /> // `style.transform` could be a string, but it's not accepted
}
```

2023-08-09 14:47 UTC, tomekzaw requested changes

2023-08-09 14:47 UTC, tomekzaw commented on __typetests__/react-native-reanimated-tests.tsx
>      // @ts-expect-error should only work for Animated refs?
```suggestion
    // @ts-expect-error should only work for Animated refs
```

2023-08-09 14:47 UTC, tomekzaw commented on src/reanimated2/index.ts
> +  TransformArrayType,
```suggestion
  TransformArrayElementType,
```

2023-08-09 14:47 UTC, tomekzaw commented on src/reanimated2/helperTypes.ts
> +export type AnimatedTransform =
The name of `AnimatedTransform` should be analogous to `TransformStyle` but currently it isn't.

2023-08-09 14:47 UTC, tomekzaw commented on src/reanimated2/layoutReanimation/animationBuilder/Keyframe.ts
> +      if (styleProp === 'transform' && Array.isArray(initialValues.transform)) {
Shouldn't we split it into separate conditionals?
```suggestion
      if (styleProp === 'transform') {
        if (Array.isArray(initialValues.transform)) {
```

2023-08-11 12:37 UTC, tomekzaw approved these changes

2023-08-11 12:38 UTC, tomekzaw commented on src/reanimated2/layoutReanimation/defaultTransitions/EntryExitTransition.ts
> +        ) {
this changes the behavior

2023-08-18 10:21 UTC, tjzel commented
Superseded by #4923

2023-08-18 10:21 UTC, closed without merging