TBD
software-mansion/react-native-reanimated pull request #4997
Opened 2023-08-28 08:42 UTC by Latropos

## Summary
Closes #4816
TBD

## Test plan

2023-08-28 09:04 UTC, tjzel reviewed
TO BE REVIEWED

2023-09-01 09:04 UTC, piaskowyk requested changes

2023-09-01 09:04 UTC, piaskowyk commented on apple/LayoutReanimation/REASwizzledUIManager.mm
> +      }
This solution can cause a memory leaks unfortunately. I think we should call removeAnimationsFromSubtree for every view from permanentlyRemovedChildren array.

2023-09-04 09:25 UTC, Latropos commented on apple/LayoutReanimation/REAAnimationsManager.m
> +- (BOOL)hasLayoutAnimation:(REAUIView *)view
* I've found that `wantsHandleRemovalOfView` so I've removed it
* I've made the function more universal, however we already have function `hasLayoutAnimation` with similar arguments doing the same on different level on abstraction. So maybe I should keep the name?

2023-09-11 18:27 UTC, piaskowyk commented on apple/LayoutReanimation/REASwizzledUIManager.mm
> +      }
@Latropos ⬆️ bump

2023-09-21 15:49 UTC, piaskowyk approved these changes
The original source of this issue was this line:
`removeAnimationsFromSubtree:(REAUIView *)container`
Since container represents an entire screen stack, every layout animation config for that stack is being removed after a screen change. Instead, we should only remove the configuration for the specific screen from the `permanentlyRemovedChildren`.

2023-09-21 17:18 UTC, merged