added React Native with Expo modules on Workflow options
software-mansion/react-native-reanimated pull request #5062
Opened 2023-09-11 12:22 UTC by efstathiosntonas

this option was missing from `bug-report.yml`

2023-09-11 12:23 UTC, efstathiosntonas commented
I don't know if the already existent workflows trigger any CI when the issue was submitted or it's just for reference 🤔

2023-09-11 20:57 UTC, efstathiosntonas commented
sorry for the commit mess, please squash it :/

2023-09-12 11:12 UTC, tjzel commented
Don't worry about the commits, we always auto-squash 😄

2023-09-12 11:35 UTC, tjzel requested changes

2023-09-12 11:35 UTC, tjzel commented on .github/ISSUE_TEMPLATE/bug-report.yml
>          - Expo managed workflow
According to @lukmccall it's outdated anyway. We can make it more actual:

```suggestion
      description: How your application is managed?
      options:
        - React Native 
        - Expo Go
        - Expo Dev Client
```

2023-09-12 11:38 UTC, efstathiosntonas commented
@tjzel you're right!

2023-09-12 11:40 UTC, tjzel commented on .github/ISSUE_TEMPLATE/bug-report.yml
> +      description: How your application is managed?
When I read this again it sounded weird 😅 

```suggestion
      description: How is your application managed?
```

2023-09-12 11:40 UTC, tjzel approved these changes

2023-09-12 11:40 UTC, merged