Get rid of native=true from ReanimatedModule
software-mansion/react-native-reanimated pull request #5134
Opened 2023-09-25 11:50 UTC by Latropos

## Summary

## Test plan

2023-09-25 15:52 UTC, tjzel requested changes

2023-09-25 15:52 UTC, tjzel commented on src/createAnimatedComponent/InlinePropManager.ts
> +      const maybeViewRef = shouldBeUseWeb()
No need to evaluate it here each time. Instead evaluate `IS_NATIVE` in top level of this file.

2023-09-25 15:52 UTC, tjzel commented on src/reanimated2/hook/useAnimatedStyle.ts
> +  const maybeViewRef = shouldBeUseWeb() ? viewsRef : undefined;
Also evaluate it in the top level of the file.

2023-09-25 15:52 UTC, tjzel commented on src/reanimated2/WorkletEventHandler.ts
> +    if (shouldBeUseWeb()) {
top level

2023-09-25 15:52 UTC, tjzel commented on src/reanimated2/mutables.ts
> +  if (!oneWayReadsOnly && !shouldBeUseWeb()) {
Definitely top level here.

2023-09-27 08:43 UTC, tjzel approved these changes
Looks good, but make sure to check if it works on Web and simulators

2023-09-27 12:56 UTC, piaskowyk requested changes
Everything look great, but please confirm that it works on Web and MacOS too

2023-09-27 14:22 UTC, piaskowyk approved these changes

2023-09-27 14:58 UTC, merged