Prevent top-level calls to `requestAnimationFrame`
software-mansion/react-native-reanimated pull request #5136
Opened 2023-09-25 12:41 UTC by bartlomiejbloniarz

## Summary

Currently there are instances where `scheduleOnUiImmediately` is called in the top level to create global structures which are not needed on web. This results in a call to `requestAnimationFrame`, which is unavailable during static website generation. We already have a mock for `raf` which prevents the error, but in this PR I changed the logic so the unnecessary calls to `raf` don't happen on web.

## Test plan

2023-09-25 14:04 UTC, tjzel requested changes

2023-09-25 14:04 UTC, tjzel commented on src/reanimated2/layoutReanimation/sharedTransitions/ProgressTransitionManager.ts
> +      '[Reanimated] ProgressTransitionRegister should not be used on web.'
```suggestion
      '[Reanimated] `ProgressTransitionRegister` is not available on non-native platform.'
```

2023-09-25 15:11 UTC, tjzel requested changes

2023-09-25 15:11 UTC, tjzel commented on src/reanimated2/UpdateProps.ts
> +    if (!isJest()) {
Please add a comment about why do we have to if `jest` out here.

2023-09-25 15:11 UTC, tjzel commented on src/reanimated2/layoutReanimation/sharedTransitions/ProgressTransitionManager.ts
> +    if (!isJest()) {
Please add a comment about why do we have to if `jest` out here.

2023-09-25 15:56 UTC, tjzel approved these changes

2023-09-25 15:56 UTC, tjzel commented
Please double check if web behavior is still proper.

2023-09-26 10:52 UTC, piaskowyk approved these changes

2023-09-26 10:53 UTC, merged