Add `layoutAnimationConfig` to docs.
software-mansion/react-native-reanimated pull request #5160
Opened 2023-09-28 14:45 UTC by bartlomiejbloniarz

## Summary

This PR adds `LayoutAnimationConfig` to docs.

## Test plan

2023-10-02 07:28 UTC, kacperkapusciak requested changes
Yoo amazing job 👏  I've left only a couple of nit-picks but nothing is a major deal-breaker

2023-10-02 07:28 UTC, kacperkapusciak commented on docs/package.json
> +    "react-native-reanimated": "3.6.0-nightly-20230928-2216f91c4",
Change to `yarn.lock` is missing in this PR. Please commit changes to `yarn.lock` too

2023-10-02 07:28 UTC, kacperkapusciak commented on docs/docs/layout-animations/layout-animation-config.mdx
> +- You can nest the `LayoutAnimationConfig` wrapper if you want to disable animations on a smaller subset of components.
Add an additional new line after this line so that two em dashes are separated

2023-10-02 07:28 UTC, kacperkapusciak commented on docs/docs/layout-animations/layout-animation-config.mdx
> +# Skipping Layout Animations
```suggestion
---
sidebar_position: 5
title: LayoutAnimationConfig
sidebar_label: Skipping Layout Animations
---
```
Let's change it so in the sidebar says `Skipping Layout Animations` but the title of the page is `LayoutAnimationConfig`

2023-10-02 07:28 UTC, kacperkapusciak commented on docs/docs/layout-animations/layout-animation-config.mdx
> +`LayoutAnimationConfig` is a wrapper that lets you skip entering and exiting animations.
```suggestion
`LayoutAnimationConfig` is a component that lets you skip entering and exiting animations.
```

2023-10-02 07:28 UTC, kacperkapusciak commented on docs/docs/layout-animations/layout-animation-config.mdx
> +} from 'react-native-reanimated';
```suggestion
import { LayoutAnimationConfig } from 'react-native-reanimated';
```

This is debatable but everywhere else in the documentation I've only imported the function on which the documentation says about at that page eg. https://docs.swmansion.com/react-native-reanimated/docs/core/useAnimatedStyle#reference

Full working example is usually in the `Example` section. The reference is just the gist about the feature.

Again, that's debatable. I'm okay with having all the imports but we'd have to make it consistent across all pages.

2023-10-02 07:28 UTC, kacperkapusciak commented on docs/docs/layout-animations/layout-animation-config.mdx
> +    </LayoutAnimationConfig>
```suggestion
    // highlight-next-line
    <LayoutAnimationConfig skipEntering>
      <View>
        {show && <Animated.View entering={PinwheelIn} exiting={PinwheelOut} />}
      </View>
      // highlight-next-line
    </LayoutAnimationConfig>
```

Let's highlight the most important part

![814hrz](https://github.com/software-mansion/react-native-reanimated/assets/39658211/220e5bfe-3f50-43ab-a11d-2c7d2dda630f)

2023-10-02 07:28 UTC, kacperkapusciak commented on docs/docs/layout-animations/layout-animation-config.mdx
> +- You can nest the `LayoutAnimationConfig` wrapper if you want to disable animations on a smaller subset of components.
```suggestion
- You can nest the `LayoutAnimationConfig` component if you want to disable animations on a smaller subset of components.
```

2023-10-04 13:41 UTC, kacperkapusciak approved these changes
🚢 🇮🇹 🎉

2023-10-04 13:42 UTC, merged

2023-10-09 21:28 UTC, tomekzaw commented
Can we do anything about it?

<img width="707" alt="LayoutAnimationConfig" src="https://github.com/software-mansion/react-native-reanimated/assets/20516055/3c03db9f-068b-42d5-ae8e-9821f1a5ef08">

2023-10-11 06:19 UTC, kacperkapusciak commented
@tomekzaw this should work now 👍 

![image](https://github.com/software-mansion/react-native-reanimated/assets/39658211/3ab5debe-0cc2-4960-a50e-4de089956524)