Remove sourceMaps on web
software-mansion/react-native-reanimated pull request #5200
Opened 2023-10-09 10:29 UTC by bartlomiejbloniarz

## Summary

This PR removes sourceMaps on web, significantly reducing the bundle size. The main change is introduced in `util.ts`. Remaining changes were introduced for bundle size testing purposes.

## Test plan
Run `yarn build` in `NextExample`. The difference between `reanimated.js` and `noreanimated.js` should be around 50KB.

2023-10-09 11:32 UTC, tomekzaw approved these changes
LGTM, left some minor suggestions.

2023-10-09 11:32 UTC, tomekzaw commented on NextExample/next.config.js
> +    // config.optimization.minimizer = [];
Can we enable this conditionally based on some constant or environmental variable?

2023-10-09 11:32 UTC, tomekzaw commented on NextExample/pages/noreanimated.js
> +      <Text style={styles.link} accessibilityRole="link" href={`/`}>
```suggestion
      <Text style={styles.link} accessibilityRole="link" href="/">
```

2023-10-09 11:32 UTC, tomekzaw commented on NextExample/pages/reanimated.js
> +      <Animated.Text style={styles.link} accessibilityRole="link" href={`/`}>
```suggestion
      <Animated.Text style={styles.link} accessibilityRole="link" href="/">
```

2023-10-09 11:32 UTC, tomekzaw commented on NextExample/next.config.js
> +  enabled: process.env.ANALYZE === 'true',
Usually environmental variables are enabled with `1`, what do you think?

2023-10-09 20:06 UTC, tomekzaw commented on NextExample/next.config.js
> +  enabled: process.env.ANALYZE === '1',
I'm afraid `ANALYZE` is not informative enough, can we rename it to `ANALYZE_BUNDLE` or `ENABLE_BUNDLE_ANALYZER`?

2023-10-09 20:06 UTC, tomekzaw commented on NextExample/next.config.js
> +const disableMinification = process.env.DISABLE_MINIFICATION === '1';
Can we add a short comment here about the effect of this flag?

2023-10-10 07:49 UTC, piaskowyk requested changes

2023-10-10 07:49 UTC, piaskowyk commented on NextExample/next.config.js
> +    }
I think we should add to documentation information what does mean DISABLE_MINIFICATION and ANALYZE, and how to use it.

2023-10-12 13:21 UTC, tjzel requested changes

2023-10-12 13:21 UTC, tjzel commented on plugin/src/utils.ts
> +    process.env.BABEL_ENV?.match(regex) || process.env.NODE_ENV?.match(regex)
```suggestion
  const pattern = /(prod|release|stag[ei])/i;
  return !!(
    process.env.BABEL_ENV?.match(pattern) || process.env.NODE_ENV?.match(pattern)
```

2023-10-12 13:21 UTC, tjzel commented on NextExample/pages/noreanimated.js
> +export default function Reanimated() {
Or `App` or something else, `Reanimated` is weird here.
```suggestion
export default function Page() {
```

2023-10-13 10:06 UTC, tjzel approved these changes

2023-10-13 15:34 UTC, piaskowyk approved these changes

2023-10-13 15:34 UTC, merged