Substitute `isWeb` and `shouldBeUseWeb` with true on web.
software-mansion/react-native-reanimated pull request #5283
Opened 2023-10-20 11:33 UTC by bartlomiejbloniarz

## Summary

This PR changes the Babel plugin to substitute `isWeb()` and `shouldBeUseWeb()` calls with `true` so that Webpack is able to recognize dead code.

## Test plan

2023-10-22 08:13 UTC, tomekzaw reviewed
I have a crazy idea, why don't we just create a new file `PlatformChecker.web.ts` with the following contents? 😄 

```ts
function isWeb() {
  return true;
}

function shouldBeUseWeb() {
  return true;
}

// ...
```

2023-12-22 09:58 UTC, tjzel requested changes

2023-12-22 09:58 UTC, tjzel commented on plugin/src/plugin.ts
> +          });
We have to keep in mind this won't transform `shouldBeUseWeb` or `isWeb` inside worklets. While it's not a valid case to call them there, we should at least have it included in tests.

2023-12-22 09:58 UTC, tjzel commented on plugin/src/types.ts
I don't quite remember, didn't we agree to use some better names here? Or was this regarding some other PR.

2023-12-22 10:30 UTC, bartlomiejbloniarz commented on plugin/src/types.ts
We agreed on `omitNativeOnlyData` in a separate pr. I just need to merge those changes here.

2023-12-22 15:01 UTC, tjzel approved these changes
Me likes 🌵

2023-12-22 15:03 UTC, merged