Restore partial support for DEBUG macro
software-mansion/react-native-reanimated pull request #5366
Opened 2023-11-10 17:10 UTC by tjzel

## Summary

This PR aims to fix the issue when Release builds would fail on Paper on iOS.
The reason this regression happened is #5113.

XCode ships by default to new projects `DEBUG` macro for Debug Configuration. Due to some issues (#4902) we decided to switch over to `NDEBUG` macro. However, the `NDEBUG` is not provided by XCode out of the box. Incidentally, it's provided by React Native which puts its install script into project's Podfile - however, [only in Fabric](https://github.com/facebook/react-native/commit/421df9ffd58092b1a2dec455a048edb6db1739de). 
What is more, some time ago React Native made it so `PRODUCTION=1 pod install` is [no longer a necessary step](https://github.com/facebook/react-native/commit/93fdcbaed0f69b268e1ae708a52df9463aae2d53) to make a release build, therefore we cannot rely on it. Until React Native defines `NDEBUG` for Paper too we have to detect, based on available options, whether we potentially have a Release build and this pull request does this.

## Test plan

Run all example apps (except TVOS cause I couldn't make it cooperate with me, and Web) on both iOS and Android in both Release and Debug and see if they work properly (e.g. add a throw in #ifndef fragment).

2023-11-10 17:11 UTC, tjzel commented on apple/RNReanimated.xcodeproj/project.pbxproj
This isn't necessary unless the library get's pre-compiled.

2023-11-16 17:35 UTC, tomekzaw requested changes

2023-11-16 17:35 UTC, tomekzaw commented on TVOSExample/ios/TVOSExample.xcodeproj/xcshareddata/xcschemes/TVOSExample-tvOS.xcscheme
> +      buildConfiguration = "Release"
revert it

2023-11-16 17:35 UTC, tomekzaw commented on Common/cpp/Tools/ReanimatedMacros.h
> +#ifdef __APPLE__
Let's swap these lines to be consistent with the description above.
```suggestion
#ifdef __APPLE__
#ifndef NDEBUG
```

2023-11-20 11:57 UTC, tjzel commented on apple/RNReanimated.xcodeproj/project.pbxproj
This might be required for pre-compilation.

2023-11-20 11:59 UTC, tomekzaw approved these changes
i like it

2023-11-20 13:35 UTC, merged