With clamp documentation
software-mansion/react-native-reanimated pull request #5381
Opened 2023-11-16 15:51 UTC by Latropos

## Summary

## Test plan

2023-11-23 14:32 UTC, kacperkapusciak requested changes

2023-11-23 14:32 UTC, kacperkapusciak commented on docs/docs/animations/withClamp.mdx
> +
A real-life example of use that's copy-paste-runable is more than welcome here

2023-11-23 14:32 UTC, kacperkapusciak commented on docs/src/components/InteractivePlayground/useClampPlayground/index.jsx
And could we have that written in TypeScript? 🙏

2023-11-23 14:32 UTC, kacperkapusciak commented on docs/src/components/InteractivePlayground/useClampPlayground/index.jsx
> +`
```suggestion
  const code = `{
  width: withClamp(
    { min: ${lowerBound}, max: ${upperBound} },
    withSpring(width.value)
  ),
}
`
```

A little bit more readable

2023-11-23 14:32 UTC, kacperkapusciak commented on docs/docs/animations/withClamp.mdx
> +
and it's missing what this function is returning

2023-11-23 14:32 UTC, kacperkapusciak commented on docs/src/components/InteractivePlayground/useClampPlayground/index.jsx
> +      label="Scope of movement"
I don't like this label as the scope of movement says nothing. This is the value to which the spring is finishing at 🤔

2023-11-23 14:32 UTC, kacperkapusciak commented on docs/src/components/InteractivePlayground/useClampPlayground/example.tsx
Files with components usually start with a capital letter

2023-11-23 14:32 UTC, kacperkapusciak commented on docs/src/components/InteractivePlayground/useClampPlayground/example.tsx
> +export default function useClampPlayground({ options }): Props {
```suggestion
export default function App({ options }): Props {
```

2023-11-23 14:32 UTC, kacperkapusciak commented on docs/src/components/InteractivePlayground/useClampPlayground/example.tsx
> +    flexDirection: 'column',
```suggestion
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
```

lets center it a bit

2023-11-23 14:32 UTC, kacperkapusciak commented on docs/src/components/InteractivePlayground/useClampPlayground/example.tsx
> +        title="toggle"
please add a vertical margin to this button 🙏

2023-11-27 08:38 UTC, kacperkapusciak commented on docs/src/components/InteractivePlayground/index.tsx
> +              value={value[idx]}
You're also missing a `key` prop on a loop

2023-11-30 13:50 UTC, kacperkapusciak requested changes

2023-11-30 13:50 UTC, kacperkapusciak commented on docs/docs/animations/withClamp.mdx
> +    clampedAnimation: T): T;
formatting and typo
```suggestion
function withClamp <T extends number | string>(config: {
    min?: T;
    max?: T;
}, clampedAnimation: T) => T;
```

2023-12-01 09:05 UTC, piaskowyk commented
I think that this example is too complex. Although I understand how clamp works, but when I look at this particular example, I feel confused. Is it possible to simplify it? Maybe we can use vertical lines as a clamp boundaries instead of rectangles, similar to the example with interpolation. cc @kacperkapusciak

2023-12-12 13:31 UTC, Latropos commented
@piaskowyk
Is it less confusing with color hints?
<img width="863" alt="image" src="https://github.com/software-mansion/react-native-reanimated/assets/56199675/392a6075-bd6b-46e6-bed0-8837fae1020f">

2023-12-18 12:17 UTC, kacperkapusciak commented on docs/docs/animations/withClamp.mdx
> +    }, clampedAnimation: T): T;
```suggestion
function withClamp<T extends number | string>(config: {
  min?: T;
  max?: T;
}, clampedAnimation: T): T;
```

2023-12-18 12:21 UTC, kacperkapusciak commented on docs/src/components/InteractivePlayground/useClampPlayground/Example.tsx
> +  });
```suggestion
  const clampedStyle = useAnimatedStyle(() => {
    return {
      transform: [
        {
          translateX: withClamp(
            { min: options.lowerBound, max: options.upperBound },
            withRepeat(
              withSequence(
                withDelay(2000, withSpring(BOX_STOP, config)),
                withTiming(BOX_START, { duration: 0 })
              ),
              -1,
              true
            )
          ),
        },
      ],
    };
  });
```

Always prefer `transform` to position props like `left`, `right`, `top`, `bottom` as they trigger layouting process and can cause jitter (see the borders)

`left`:

https://github.com/software-mansion/react-native-reanimated/assets/39658211/815dddf8-37e8-4eb7-ab1f-26dc214eda43


`translateX`:

https://github.com/software-mansion/react-native-reanimated/assets/39658211/a8f6ffba-9f2f-4167-bc41-7ab1bb3222d8

2023-12-18 12:22 UTC, kacperkapusciak commented on docs/src/components/InteractivePlayground/useClampPlayground/Example.tsx
> +  });
```suggestion
  const defaultStyle = useAnimatedStyle(() => {
    return {
      transform: [
        {
          translateX: withRepeat(
            withSequence(
              withDelay(2000, withSpring(200, config)),
              withTiming(0, { duration: 0 })
            ),
            -1,
            true
          ),
        },
      ],
    };
  });
```

2023-12-21 11:07 UTC, kacperkapusciak approved these changes
🎉

2023-12-21 11:52 UTC, merged