Make /app good for for 0.74
software-mansion/react-native-reanimated pull request #5830
Opened 2024-03-25 10:38 UTC by tjzel

## Summary

This PR is a part of ongoing effort to bring Reanimated to React Native 0.74 with bridgeless mode. It consists of following Pull Requests, which are split for review convenience - but shouldn't be considered separate entities. They have to be merged in the following order:

- #5830
- #5815
- #5834
- #5734 

## Test plan

:shipit:

2024-03-25 14:26 UTC, tjzel commented on app/src/examples/AboutExample.tsx
> +            {(global as any)._IS_BRIDGELESS ? 'yes' : 'no'}
I did to print it in `AboutExample` 🤣. We can remove it if we don't want it.

2024-03-25 14:44 UTC, piaskowyk commented on app/src/examples/AboutExample.tsx
> +            {(global as any)._IS_BRIDGELESS ? 'yes' : 'no'}
I'm ok with that 😅

2024-03-26 07:51 UTC, piaskowyk approved these changes
For me is legit 🫡  Before merging:
- Let's sort out the CI - https://github.com/software-mansion/react-native-reanimated/actions/runs/8421856626/job/23059739159?pr=5830
- Wait for approval on https://github.com/software-mansion/react-native-reanimated/pull/5815, and then let's merge both pull requests together to keep the main branch in a consistent state.

2024-03-26 09:22 UTC, tjzel commented on app/package.json
>      "react-native-web": "~0.18.12"
I have them all upgraded in other PRs 👍

2024-03-26 12:30 UTC, tomekzaw requested changes

2024-03-26 12:30 UTC, tomekzaw commented on app/src/examples/LiquidSwipe/LiquidSwipe.tsx
> +  const ctxStartY = useSharedValue(0);
remove `ctx`

2024-03-26 12:30 UTC, tomekzaw commented on app/src/examples/AboutExample.tsx
> +            {(global as any)._IS_BRIDGELESS ? 'yes' : 'no'}
move to `isBridgeless()`

2024-03-26 12:30 UTC, tomekzaw commented on app/src/examples/ScreenStackHeaderConfigBackgroundColorExample.tsx
> +    ? React.forwardRef(ScreenStackHeaderConfig as any)
😢

2024-03-26 13:11 UTC, tomekzaw approved these changes

2024-03-27 12:37 UTC, merged