Use one constructor for NativeReanimatedModule with bridgeless
software-mansion/react-native-reanimated pull request #5868
Opened 2024-04-04 12:45 UTC by tjzel

## Summary

@tomekzaw wanted this badly

## Test plan

2024-04-04 18:33 UTC, tomekzaw requested changes
@tjzel Thanks again for your effort.

General feedback: Why don't we just instantiate `JSScheduler` before calling `NativeReanimatedModule` ctor? This way we can avoid adding `JSScheduleDependencyHolder` to our codebase class at all.

The only obstacle is that we need to pass `rnRuntime` along with `jsInvoker` (in bridgeful mode) but this is not a real problem as we luckily have access to it without any problem. In bridgeless mode, we don't need `rnRuntime` at all.

2024-04-04 18:33 UTC, tomekzaw commented on Common/cpp/NativeModules/NativeReanimatedModule.cpp
> +  return runtimeExecutor_;
```suggestion
  react_native_assert(runtimeExecutor_ != nullptr);
  return runtimeExecutor_;
```
or
```suggestion
  react_native_assert(isBridgeless());
  return runtimeExecutor_;
```

2024-04-04 18:33 UTC, tomekzaw commented on android/src/main/cpp/NativeProxy.cpp
> +          JSSchedulerDependencyHolder(jsCallInvoker),
```suggestion
          std::make_shared<JSScheduler>(rnRuntime, jsCallInvoker),
```

2024-04-04 18:33 UTC, tomekzaw commented on apple/native/NativeProxy.mm
> +  JSSchedulerDependencyHolder jsSchedulerDependencyHolder(jsInvoker);
```suggestion
  auto jsScheduler = std::make_shared<JSScheduler>(rnRuntime, jsInvoker);
```

2024-04-04 18:33 UTC, tomekzaw commented on apple/native/NativeProxy.mm
> +      rnRuntime, jsSchedulerDependencyHolder, jsQueue, uiScheduler, platformDepMethodsHolder, valueUnpackerCode);
```suggestion
      rnRuntime, jsScheduler, jsQueue, uiScheduler, platformDepMethodsHolder, valueUnpackerCode);
```

2024-04-05 12:11 UTC, tomekzaw commented on Common/cpp/Tools/JSScheduler.h
>    const std::function<void(Job)> scheduleOnJS = nullptr;
Can we make it private?

2024-04-05 12:11 UTC, tomekzaw commented on Common/cpp/Tools/JSScheduler.h
> +  const std::shared_ptr<CallInvoker> getJSCallInvoker() const;
Let's move this declaration right after `JSScheduler` constructor (we already have `public:` there).

2024-04-05 12:12 UTC, tomekzaw commented on android/src/main/cpp/NativeProxy.cpp
> +          std::make_shared<JSScheduler>(*rnRuntime, jsCallInvoker),
Let's construct `JSScheduler` before:

```cpp
auto jsScheduler = std::make_shared<JSScheduler>(*rnRuntime, jsCallInvoker);
```

2024-04-05 12:13 UTC, tomekzaw commented on android/src/main/cpp/NativeProxy.cpp
> +          std::make_shared<JSScheduler>(*rnRuntime, runtimeExecutor),
same as above

2024-04-05 13:18 UTC, tjzel commented on android/src/main/cpp/NativeProxy.cpp
> +          std::make_shared<JSScheduler>(*rnRuntime, jsCallInvoker),
no can do (it's an initializer list)

2024-04-05 13:18 UTC, tjzel commented on android/src/main/cpp/NativeProxy.cpp
> +          std::make_shared<JSScheduler>(*rnRuntime, runtimeExecutor),
no can do (it's an initializer list)

2024-04-05 13:19 UTC, tjzel commented on android/src/main/cpp/NativeProxy.cpp
> +          true)),
no can do (it's an initializer list)

2024-04-05 14:19 UTC, tjzel commented on Common/cpp/Tools/JSScheduler.cpp
> +// DO NOT USE OR YOU WILL BE PROMOTED
😢

2024-04-05 14:49 UTC, tomekzaw approved these changes
Thanks for fixing this! ❤️

2024-04-05 14:54 UTC, merged