initial cspell
software-mansion/react-native-reanimated pull request #5888
Opened 2024-04-11 08:42 UTC by xnameTM

## Summary
Testing CI jobs

2024-04-15 10:44 UTC, tjzel commented on .github/workflows/spellcheck.yml
> +                use_cspell_files: false
newline 😎

2024-04-15 10:44 UTC, tjzel commented on cspell.json
> +}
newline 😎

2024-04-15 12:25 UTC, tjzel approved these changes
:shipit:

2024-04-15 12:53 UTC, tomekzaw requested changes

2024-04-19 08:57 UTC, tomekzaw commented on .github/workflows/spellcheck.yml
> +          use_cspell_files: false
Let's add a newline at the end of the document

2024-04-19 08:57 UTC, tomekzaw commented on .github/workflows/spellcheck.yml
> +      - main
Let's add like in other `.yml` files
```
  merge_group:
    branches:
      - main
```

2024-04-19 08:58 UTC, tomekzaw commented on cspell.json
> +{
Let's use 2 spaces here as well

2024-04-19 09:08 UTC, tomekzaw requested changes
Left some minor suggestions in the comments

2024-04-19 10:49 UTC, xnameTM commented on .github/workflows/spellcheck.yml
> +      - main
ok

2024-04-19 14:02 UTC, tomekzaw approved these changes
Thanks!

2024-04-21 20:46 UTC, merged