Make animated components use different tags for events
software-mansion/react-native-reanimated pull request #5960
Opened 2024-04-30 15:53 UTC by szydlovsky

## Summary

Turns out the usual component tag (used for Layout Animations, Shared Element Transitions and Animated Styles) won't always work for events if the component with nested event emitters is made animated. Thus I am splitting these two into different tag variables.

## Test plan

You can check out the following code (logs in console): 
<details><summary>Code</summary>

``` TYPESCRIPT
import React from 'react';
import Animated, { useAnimatedScrollHandler } from 'react-native-reanimated';
import { StyleSheet, View, Text } from 'react-native';
import { FlashList } from '@shopify/flash-list';

const AnimatedFlashList = Animated.createAnimatedComponent(FlashList);

const data = new Array(45);

export default function EmptyApp() {
  const scrollHandler = useAnimatedScrollHandler(
    {
      onBeginDrag: () => {
        'worklet';
        console.log('ON BEGIN DRAG');
      },
      onScroll: () => {
        'worklet';
        console.log('ON SCROLL');
      },
      onMomentumEnd: () => {
        'worklet';
        console.log('ON END');
      },
    },
    []
  );

  const renderFlashListItem = () => {
    return <View style={styles.itemFlash} />;
  };

  const renderFlatListItem = () => {
    return <View style={styles.itemFlat} />;
  };

  return (
    <View style={styles.container}>
      <View style={styles.listContainer}>
        <Text>Animated FlashList</Text>
        <AnimatedFlashList
          onScroll={scrollHandler}
          renderItem={renderFlashListItem}
          data={data}
          estimatedItemSize={40}
        />
      </View>
      <View style={styles.listContainer}>
        <Text>Animated FlatList</Text>
        <Animated.FlatList
          onScroll={scrollHandler}
          renderItem={renderFlatListItem}
          data={data}
        />
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: 'row',
  },
  listContainer: {
    flex: 1,
    flexDirection: 'column',
  },
  itemFlash: {
    width: 20,
    height: 20,
    backgroundColor: 'red',
    margin: 10,
  },
  itemFlat: {
    width: 20,
    height: 20,
    backgroundColor: 'green',
    margin: 10,
  },
});

```
</details>

Current tests work on:

- [x] Paper
- [x] Fabric
- [x] Web

2024-05-03 07:48 UTC, gronxb commented
I haven't checked detail, but `gorhom/react-native-bottom-sheet` was behaving strangely after applying that patch.

2024-05-03 09:55 UTC, szydlovsky commented
@gronxb if you were able to provide a small example where the react-native-bottom-sheet behaves strangely I’d be able to check it out and make sure it works as well

2024-05-03 09:58 UTC, gronxb commented
I've been busy and haven't prepared a repro, I'll do it as soon as I can.

When calling Pressable onPress from within the bottom sheet, the bottom sheet is forced down.

2024-05-06 14:46 UTC, tjzel requested changes
While it's fine for me that we might have two tags, first for events and the second for other operations, I think that we should focus on the "why" here.

1. How comes that we actually need two different tags? Do all operations that require `_componentViewTag` work properly when `_eventViewTag` is correct

2. Why didn't we need it before? Which change exactly forces us to make the split here? Or maybe it was always like this and only now we have detected it?

3. What about `useScrollViewOffset` here? Is it always able to get the tag it actually requires?

We definitely need to try to answer those questions.

2024-05-06 15:09 UTC, gronxb commented
@szydlovsky 

Sorry for the delay, here's the reproduction, I think it's the backdrop, if you press anywhere on the bottom sheet, it forces it to go down.

If I don't apply that patch, it only goes down normally when I press backdrop. 

It seems like something conflicts and thinks backdrop is pressed even if you press anywhere.

https://github.com/gronxb/reanimated-repro/blob/main/App.tsx

* Apply Patch 

https://github.com/software-mansion/react-native-reanimated/assets/41789633/9bdc88fa-de0e-4bad-a79b-e08a86145749

* No Patch

https://github.com/software-mansion/react-native-reanimated/assets/41789633/ead7ab65-8a66-4f18-a576-be11797f9a29

2024-05-07 14:30 UTC, szydlovsky commented
@gronxb alright I found the issue, could you please try out this patch - 
[react-native-reanimated+3.11.0.patch](https://github.com/software-mansion/react-native-reanimated/files/15236996/react-native-reanimated%2B3.11.0.patch)

2024-05-07 15:09 UTC, gronxb commented
@szydlovsky  it works fine 👍

2024-05-07 15:20 UTC, szydlovsky commented
@tjzel `@gorhom/bottom-sheets` now works fine with the fix AND turns out `useScrollViewOffset` gets its tags very well for all scenarios (Web/Paper/Fabric) - it didn't need any changes. Therefore it is now reviewable again

2024-05-08 11:55 UTC, tjzel commented
@szydlovsky I assume you tested it natively on iOS only? Android can have a different view hierarchy, please check it too.

Is this PR something that could be verified by runtime tests?

2024-05-08 12:14 UTC, szydlovsky commented
@tjzel I tested it on all: iOS and Android (both Paper and Fabric) and Web. Works fine everywhere. If it comes to runtime tests, we would have to use `flash-list` and `botom-sheets` as dependencies so I am not so sure - taking under consideration that this fix is quite highly demanded.

2024-05-08 12:50 UTC, tjzel commented
Oh, that's great then! We can list those as dev dependencies, that's not a problem, but let's not incorporate 3rd party libraries into our runtime tests yet. I will add it as a potential task for the future.

2024-05-08 12:52 UTC, tjzel approved these changes
Looks good to me, but I'd like @piaskowyk or @tomekzaw to take a look at it as well.

2024-05-08 13:51 UTC, tomekzaw approved these changes

2024-05-08 14:53 UTC, merged

2024-05-21 14:01 UTC, ChadyAyoub4 commented
@szydlovsky Works perfectly.

2024-05-21 18:49 UTC, sraut1 commented
@szydlovsky I am facing this issue https://github.com/software-mansion/react-native-reanimated/issues/4730. 
should this patch fix this one too?

2024-05-21 18:58 UTC, szydlovsky commented
@sraut1 This patch will be in the next release ***after*** 3.11. And no, this one most likely doesn't fix the issue since it has nothing to do with animated styles. Nevertheless, feel free to [use the patch](https://github.com/software-mansion/react-native-reanimated/pull/5960#issuecomment-2098548412), maybe it sorts something out.

2024-05-21 19:28 UTC, sraut1 commented
@szydlovsky the patch fixes issue https://github.com/software-mansion/react-native-reanimated/issues/4730. thanks

2024-05-21 19:30 UTC, szydlovsky commented
@sraut1 woah, I'll let the ppl know then 🤯