docs: update Hire us to directly lead to contact form
software-mansion/react-native-reanimated pull request #6087
Opened 2024-06-07 11:49 UTC by kacperkapusciak

2024-06-07 15:30 UTC, piaskowyk approved these changes

2024-06-10 07:18 UTC, patrycjakalinska approved these changes
🚀

2024-06-10 12:46 UTC, tomekzaw commented
Let's also update the link in README.md.

2024-06-10 12:46 UTC, tomekzaw requested changes
Let's also update the link in README.md:

https://github.com/software-mansion/react-native-reanimated/blame/main/README.md#L59

2024-06-11 12:40 UTC, tomekzaw approved these changes

2024-06-11 12:41 UTC, tomekzaw requested changes
One more:
https://github.com/software-mansion/react-native-reanimated/blob/987e017c999a4ab3054cec9538e53929e133c3fa/packages/docs-reanimated/src/components/HireUsSection/index.tsx#L21

2024-06-11 12:42 UTC, tomekzaw commented on packages/docs-reanimated/src/components/HireUsSection/index.tsx
> +          href="https://swmansion.com/contact/projects?utm_source=reanimated&utm_medium=landing-page"
```suggestion
          href="https://swmansion.com/contact/projects?utm_source=reanimated&utm_medium=docs"
```

2024-06-11 13:16 UTC, merged