Modify reanimated props updates
software-mansion/react-native-reanimated pull request #6330
Opened 2024-07-25 14:57 UTC by bartlomiejbloniarz

## Summary

## Test plan

2024-07-29 16:43 UTC, tomekzaw requested changes

2024-07-29 16:43 UTC, tomekzaw commented on packages/react-native-reanimated/Common/cpp/Fabric/ReanimatedMountHook.cpp
> +    double) noexcept {}
Do we still need this mount hook?

2024-07-29 16:43 UTC, tomekzaw commented on packages/react-native-reanimated/Common/cpp/NativeModules/NativeReanimatedModule.cpp
> +          auto reaShadowNode =
Let's avoid using "rea" if needed.
```suggestion
          auto markedShadowNode =
```
or
```suggestion
          auto shadowNodeWithTrait =
```

2024-07-29 16:43 UTC, tomekzaw commented on packages/react-native-reanimated/Common/cpp/Fabric/ReanimatedCommitHook.cpp
> +  if (reaShadowNode->isReanimatedCommit()) {
```suggestion
  if (reaShadowNode->hasReanimatedCommitTrait()) {
```

2024-07-29 16:43 UTC, tomekzaw commented on packages/react-native-reanimated/Common/cpp/Fabric/ReanimatedCommitShadowNode.h
> +const ShadowNodeTraits::Trait reanimatedCommitTrait{
```suggestion
constexpr ShadowNodeTraits::Trait ReanimatedCommitTrait{
```

2024-07-29 16:43 UTC, tomekzaw commented on packages/react-native-reanimated/Common/cpp/Fabric/ReanimatedCommitShadowNode.h
> +    ShadowNodeTraits::Trait(1 << 31)};
```suggestion
    1 << 31};
```

2024-07-29 16:43 UTC, tomekzaw commented on packages/react-native-reanimated/Common/cpp/Fabric/ReanimatedCommitShadowNode.h
> +class ReanimatedCommitShadowNode : public ShadowNode {
```suggestion
class ReanimatedTraitsEnabledShadowNode : public ShadowNode {
```

2024-07-30 10:03 UTC, bartlomiejbloniarz commented on packages/react-native-reanimated/Common/cpp/Fabric/ReanimatedMountHook.cpp
> +    double) noexcept {}
no

2024-07-30 11:40 UTC, tomekzaw commented on packages/react-native-reanimated/Common/cpp/NativeModules/NativeReanimatedModule.cpp
> +          auto reaShadowNode =
Right, how about `ReanimatedTraitAccessEnabledShadowNode`? That's probably too long.

2024-07-30 11:56 UTC, tomekzaw approved these changes

2024-07-30 11:56 UTC, tomekzaw commented on packages/react-native-reanimated/Common/cpp/Fabric/ReanimatedCommitShadowNode.h
> +// the arbitarly chosen number 27 will be safe :)
```suggestion
// We use this trait to mark that a commit was created by Reanimated.
// Traits are copied when nodes are cloned, so this information
// won't be lost unless someone explicitly overrides it.
// We need this information to skip unnecessary updates in
// the commit hook.
// Currently RN traits go up to 10, so hopefully
// the arbitrarily chosen number 27 will be safe :)
```

2024-07-30 13:03 UTC, merged