chore: migrate npx react-native init
software-mansion/react-native-reanimated pull request #6628
Opened 2024-10-24 12:53 UTC by coado

## Summary

Migrating deprecated `npx react-native init` command to `npx @react-native-community/cli init` as mentioned [here](https://github.com/software-mansion/react-native-reanimated/pull/6533#pullrequestreview-2321459011)

2024-10-24 14:15 UTC, tomekzaw approved these changes

2024-10-24 14:15 UTC, tomekzaw commented
Looks good but CIs are failing

2024-10-25 14:09 UTC, tjzel commented
Let me fix Yarn & installing from commit management in https://github.com/software-mansion/react-native-reanimated/pull/6635 prior to merging it

2024-11-18 17:07 UTC, tjzel requested changes

2024-11-18 17:07 UTC, tjzel commented on .github/workflows/V8-reanimated-build-check-nightly.yml
> -        run: npx react-native init app
`npx react-native init`/`rncli init` can be unstable at times. Installing it firstly with yarn, then doing `yarn rncli init` improves stability for some reasons. Please adjust to that way of app initialization here.

2024-11-21 16:11 UTC, tjzel commented
I'm doing an aggressive takeover 😈

2024-11-22 16:58 UTC, tjzel approved these changes
Still doesn't work but it doesn't work in a better way now 🥳

2024-11-22 16:59 UTC, merged