fix: Break circular reference in `NativeProxy` and `AndroidUIScheduler`
software-mansion/react-native-reanimated pull request #6697
Opened 2024-11-12 16:33 UTC by lukmccall

## Summary

Breaks circular reference in `NativeProxy` and `AndroidUIScheduler`.
Needs https://github.com/software-mansion/react-native-reanimated/pull/6671 to work. 

`NativeProxy` and `AndroidUIScheduler` is a `HybridClass` with a C++ counterpart holding a global reference to the Java object. This structure creates a circular reference between C++ and Java, which the garbage collector cannot clean up. To resolve this issue, I manually removed the reference between C++ and Java by resetting the global ref during the invalidation of the `NativeProxy` and `AndroidUIScheduler`.

## Test plan

I tested it with a new project using Expo (SDK 52) and with Fabric enabled. I reloaded the app several times and performed a heap dump to verify that everything was removed correctly.

2024-12-24 12:48 UTC, tjzel commented on packages/react-native-reanimated/android/src/reactNativeVersionPatch/NativeProxyFabric/latest/com/swmansion/reanimated/NativeProxy.java
> +    invalidateCpp();
Shouldn't we reverse the order here?
```suggestion
    invalidateCpp();
    super.invalidate();
```

2024-12-24 12:48 UTC, tjzel commented on packages/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/AndroidUIScheduler.java
>    }
Can we rename this method to `invalidate` instead?

2024-12-24 12:48 UTC, tjzel commented on packages/react-native-reanimated/android/src/main/cpp/reanimated/android/NativeProxy.cpp
> +  }
I'm not a fan of checking this every time, but it sure is the best way if we don't want any refactors here. However, I'd much prefer something among the lines for transparency:

```suggestion
  if (invalidated) {
    return;
  }
```

What do you think?

2025-01-09 13:44 UTC, piaskowyk approved these changes
For me, the approach is okay 👍

2025-02-24 10:55 UTC, tomekzaw requested changes

2025-02-24 10:55 UTC, tomekzaw commented on packages/react-native-worklets/android/src/main/cpp/worklets/android/AndroidUIScheduler.cpp
> +  if(!uiScheduler_){
```suggestion
  if (!uiScheduler_) {
```

2025-02-24 11:09 UTC, tomekzaw approved these changes

2025-02-24 12:12 UTC, merged