fix: Make `withDecay` compatible with `withRepeat`
software-mansion/react-native-reanimated pull request #6772
Opened 2024-11-28 12:05 UTC by patrycjakalinska

## Summary

As it was discovered in #6757, `withRepeat` run with `withDecay` triggered only once, even if the number of repeats was greater. `withDecay` relies on the value of `velocity`. The `initialVelocity` is the velocity provided (or default), and during the animation, the `velocity` value decreases, causing the animated object to slowly stop. The problem was, after first repeat the `velocity` was already decreased to almost zero and the animation could not run, as it had no momentum.
I was able to fix that by adjusting `finished` prop, and reseting `velocity` to initial value, if `finished` is `true`. 

Fixes #6757 

## Test plan

Run provided code snipped on Fabric example

<details>
<summary>Code snipped provided in issue</summary>

```ts
import React from 'react';
import { View, Pressable, Text, StyleSheet } from 'react-native';
import Animated, {
  useAnimatedStyle,
  useSharedValue,
  withDecay,
  withRepeat,
} from 'react-native-reanimated';
import {
  GestureHandlerRootView,
  GestureDetector,
  Gesture,
} from 'react-native-gesture-handler';

const ballSize = 100;

export default function EmptyExample() {
  const position = useSharedValue(1);

  const animatedStyle = useAnimatedStyle(() => ({
    transform: [{ translateY: position.value }],
  }));

  const tap = Gesture.Tap().onStart(() => {
    position.value = withRepeat(
      withDecay({ velocity: 200, clamp: [-50, 100] }),
      5
    );
    // position.value = withDecay({ velocity: 200, clamp: [-500, 500] });
  });

  return (
    <GestureHandlerRootView style={{ flex: 1 }}>
      <View
        style={{ flex: 1, justifyContent: 'center', backgroundColor: 'red' }}>
        <GestureDetector gesture={tap}>
          <View
            style={{
              flex: 1,
              alignItems: 'center',
              justifyContent: 'center',
              flexDirection: 'column',
            }}>
            <Animated.View style={[styles.ball, animatedStyle]} />
          </View>
        </GestureDetector>
      </View>
    </GestureHandlerRootView>
  );
}
const styles = StyleSheet.create({
  ball: {
    width: ballSize,
    height: ballSize,
    borderRadius: ballSize / 2,
    backgroundColor: 'black',
    margin: 30,
  },
});

```

</details>

2024-12-24 12:52 UTC, tjzel commented on packages/react-native-reanimated/src/valueSetter.ts
> +      animation.finished = finished;
I'm worried about fixing this bug 🙈

2025-01-02 12:28 UTC, piaskowyk requested changes

2025-01-08 10:59 UTC, patrycjakalinska commented on packages/react-native-reanimated/src/valueSetter.ts
> +      animation.finished = finished;
It's not necessary but i don't see a logic with a previous assignment (`animation.current = true`) (?).

We have similiar situation in `useAnimatedStyle.ts` on :146

```js
      finished = animation.onFrame(animation, timestamp);
      animation.timestamp = timestamp;
      if (finished) {
        animation.finished = true;
        animation.callback && animation.callback(true /* finished */);
      }
```
but here te `animation.finished = true` is reasonable as it is in condition of `finished` prop from `onFrame`. (This is maybe even better solution than `animation.finished = finished`)

As far as I checked, my changes - especially if we stand with`useAnimatedStyle` approach:
```js
 finished = animation.onFrame(animation, timestamp);
      if (finished) {
        animation.finished = true;
      }
```
nor break nor fix anything, but only seems more resonable.

What's your opinion on that, from a more experienced perspective? 😄

2025-01-08 10:59 UTC, patrycjakalinska commented on packages/react-native-reanimated/src/animation/decay/decay.ts
> +      const initialVelocity = config.velocity ?? 0;
fixed in [e226b05](https://github.com/software-mansion/react-native-reanimated/pull/6772/commits/e226b052cc6520c0b0e0a5f2b7923d25be93b43f)

2025-01-29 12:02 UTC, piaskowyk approved these changes

2025-01-30 07:40 UTC, merged